eStore_web/eStore_web/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eStore_web.Common;
using eStore_web.EF;
using eStore_web.EF_Models;
using eStore_web.Services;
using eStore_web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace eStore_web.Controllers
{
    public class AdministratorController : Controller
    {

        eContext db = new eContext();
    
        private INotifikacije _notifikacije;

        public AdministratorController(INotifikacije notifikacije)
        {
            _notifikacije = notifikacije;
            
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult OdobriGet()
        {
            var model = db.Igra.Where(x => x.Odobrena == false).ToList();
            return View( model);
        }
        public IActionResult OdobriSet(int id)
        {

            var igra = db.Igra.Include(x => x.Developer).Where(x => x.IgraID == id).SingleOrDefault();
            if (igra == null)
                return Content("nema");
            igra.Odobrena = true;
            db.Update(igra);
            db.SaveChanges();
            _notifikacije.posaljiNotifikacije(igra.Developer.OsobaID, Autentifikacija.GetLogiraniKorisnik(HttpContext).OsobaID, new NotifikacijaVM()
            {
                Poruka = "Vasa igrica " + igra.Naziv + " je odobrena",
                Url = "/Developer/ViewGameDetails?igraID=" + igra.IgraID
            });
            return RedirectToAction(nameof(OdobriGet));
        }
        //akcija u kontroleru Administrator za poziv viewa za ispis developera

        public IActionResult Prikaz()
        {
            List<Developer> lista = db.Developer.Include("Osoba").ToList();
            ViewData["lista-developera"] = lista;
            return View();
        }
        //akcija za banovanje developera
        public IActionResult Banuj(int DeveloperID)
        {
            
            Developer developer = db.Developer.Find(DeveloperID);
            if (developer == null)
            {
                return Content("Doslo je do greske. Molim vas pokusajte kasnije.");
            }
            developer.Banovan = true;
            db.Update(developer);
            db.SaveChanges();
            db.Dispose();
            return RedirectToAction(nameof(Prikaz));
        }
        public IActionResult Unban(int DeveloperID)
        {
            Developer developer = db.Developer.Find(DeveloperID);
            if (developer == null)
            {
                return Content("Doslo je do greske. Molim vas pokusajte kasnije.");
            }
            developer.Banovan = false;
            db.Update(developer);
            db.SaveChanges();
            db.Dispose();
            return RedirectToAction(nameof(Prikaz));
        }
        //akcija za pregled igara odredjenog developera
        public IActionResult PregledIgara(int DeveloperID)
        {
            var model = new PregledIgaraAdministratorVM
            {
                Igre = db.Igra.Where(x => x.DeveloperID == DeveloperID).ToList(),
                Developer = db.Developer.Where(x => x.DeveloperID == DeveloperID).Include(x=>x.Osoba).SingleOrDefault().Osoba.Ime + " " + db.Developer.Where(x => x.DeveloperID == DeveloperID).SingleOrDefault().Osoba.Prezime
            };
            var lista = db.Igra.Where(x => x.DeveloperID == DeveloperID).ToList();
            return View(model);

           
        }
        //akcija za prikaz igara sa njihovim osnovnim podacima
        public IActionResult PrikazIgara()
        {
            
            var listaIgara = db.Igra.Include(x => x.GameGenre).Include(x => x.RatingCategorie).ToList();

            return View(listaIgara);
            
        }
        public IActionResult PremiumOn(int id)
        {
            var igra = db.Igra.Where(x => x.IgraID == id).SingleOrDefault();
            igra.PremiumStatus = true;
            db.Update(igra);
            db.SaveChanges();
            return RedirectToAction(nameof(PrikazIgara));
        }
        public IActionResult PremiumOff(int id)
        {
            var igra = db.Igra.Where(x => x.IgraID == id).SingleOrDefault();
            igra.PremiumStatus = false;
            db.Update(igra);
            db.SaveChanges();
            return RedirectToAction(nameof(PrikazIgara));
        }
        public IActionResult Detalji(int DeveloperID)
        {
            
            var developer = db.Developer.Where(x => x.DeveloperID == DeveloperID).Include(x => x.Osoba).Include(x => x.Osoba.EmailAddress).Include(x => x.Osoba.Grad).SingleOrDefault();
            var model = new AdministratorDetaljiVM
            {
                DeveloperID=developer.DeveloperID,
                ImePrezime = developer.Osoba.Ime + " " + developer.Osoba.Prezime,
                Email = developer.Osoba.EmailAddress.Email,
                DatumRodjenja = developer.Osoba.DatumRodenja,
                Kompanija = developer.NazivKompanije,
                Grad = developer.Osoba.Grad.Naziv
            };
            return View(model);
        }
        //akcija koja se poziva prilikom klika na dugme uredi, pronalazi datu igru i prosledjuje je u formu za editovanje
        [HttpGet]
        public IActionResult Uredi(int id)
        {


            var igra = db.Igra.SingleOrDefault(x => x.IgraID == id);
            var model = new AdministratorUrediVM
            {
                IgraId = igra.IgraID,
                Naziv = igra.Naziv,
                Opis = igra.Opis,
                Cijena = igra.Cijena,
                DatumObjave = igra.DatumObjave,
                Odobrena = igra.Odobrena,
                PremiumStatus = igra.PremiumStatus,
                Zanrovi = db.GameGenre.Select(x => new SelectListItem
                {
                    Value = x.GameGenreID.ToString(),
                    Text = x.NazivZanra
                }).ToList(),
                Kategorije = db.RatingCategorie.Select(x => new SelectListItem
                {
                    Value = x.RatingCategorieID.ToString(),
                    Text = x.NazivKategorije
                }).ToList()


            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Uredi(AdministratorUrediVM model)
        {
            if (!ModelState.IsValid)
            {
                model.Zanrovi = db.GameGenre.Select(x => new SelectListItem
                {
                    Value = x.GameGenreID.ToString(),
                    Text = x.NazivZanra
                }).ToList();
                model.Kategorije = db.RatingCategorie.Select(x => new SelectListItem
                {
                    Value = x.RatingCategorieID.ToString(),
                    Text = x.NazivKategorije
                }).ToList();
                return View(model);
            }
            Igra i = db.Igra.Find(model.IgraId);
            i.Naziv = model.Naziv;
            i.Cijena = model.Cijena;
            i.DatumObjave = model.DatumObjave;
            i.Opis = model.Opis;
            i.PremiumStatus = model.PremiumStatus;
            i.RatingCategorieID = model.KategorijaId;
            i.GameGenreID = model.ZanrId;
            db.Update(i);
            db.SaveChanges();
            db.Dispose();

            return RedirectToAction(nameof(PrikazIgara));
        }

        public IActionResult PrikazRefundova()
        {
            var lista = db.Refund.Include(x => x.Kupac).Include(x => x.Kupac.Osoba).Include(x => x.Igra).ToList();
            return View(lista);
        }
        public IActionResult Odbij(int id)
        {
            var refund = db.Refund.SingleOrDefault(x => x.RefundID == id);
            db.Refund.Remove(refund);
            db.SaveChanges();
            return RedirectToAction(nameof(PrikazRefundova));

        }
        public IActionResult Prihvati(int id)
        {
            var refund = db.Refund.Include(x => x.Igra).Where(x => x.RefundID == id).SingleOrDefault();
            var wallet = db.Wallet.SingleOrDefault(x => x.KupacID == refund.KupacID);
            wallet.balance += refund.Igra.Cijena;
            db.Remove(refund);
            db.Update(wallet);
            db.SaveChanges();
            return RedirectToAction(nameof(PrikazRefundova));

        }
        public IActionResult Odobri(int id)
        {
            var igra = db.Igra.SingleOrDefault(x => x.IgraID == id);
            igra.Odobrena = true;
            db.Update(igra);
            db.SaveChanges();
            return RedirectToAction(nameof(PregledIgara), new { DeveloperID = igra.DeveloperID });
        }

        public IActionResult Zabrani(int id)
        {
            var igra = db.Igra.SingleOrDefault(x => x.IgraID == id);
            igra.Odobrena = false;
            db.Update(igra);
            db.SaveChanges();
            return RedirectToAction(nameof(PregledIgara), new { DeveloperID = igra.DeveloperID });
        }

        public IActionResult GetZahtjeveZaPremium()
        {
            var lista = db.PrijavaPremium.Include(x => x.Kupac).ToList();
            return View(lista);
        }
        public IActionResult PrihvatiPremium(int id)
        {
            var zahtjev = db.PrijavaPremium.SingleOrDefault(x => x.Id == id);
            var kupac = db.Kupac.SingleOrDefault(x => x.KupacID == zahtjev.KupacId);
            kupac.PretplacenNaPremium = true;
            db.Update(kupac);
            db.Remove(zahtjev);
            db.SaveChanges();
            return RedirectToAction(nameof(GetZahtjeveZaPremium));
        }
        public IActionResult OdbijPremium(int id)
        {
            var zahtjev = db.PrijavaPremium.SingleOrDefault(x => x.Id == id);

eStore_web/eStore_web/Controllers/AjaxIgreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eStore_web.EF;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eStore_web.Controllers
{
    public class AjaxIgreController : Controller
    {
        eContext db = new eContext();
       
        public IActionResult Index(int id)
        {
            var model = db.Igra.Where(x => x.DeveloperID == id).Include(x => x.GameGenre).ToList();
            return PartialView(model);
        }
    }
}

eStore_web/eStore_web/Views/Administrator/Detalji.cshtml
@model eStore_web.ViewModel.AdministratorDetaljiVM
@{
    ViewData["Title"] = "Detalji";
}
<style>
    table {
        text-align: center;
    }
</style>
<h2>Detalji</h2>

<table class="table  table-bordered">
    <tbody>
        <tr>
            <td>Ime i prezime</td>
            <td>@Model.ImePrezime</td>
        </tr>
        <tr>
            <td>Datum rodjenja</td>
            <td>@Model.DatumRodjenja.ToShortDateString()</td>
        </tr>
        <tr>
            <td>Email adresa</td>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <td>Grad</td>
            <td>@Model.Grad</td>
        </tr>
        <tr>
            <td>Kompanija</td>
            <td>@Model.Kompanija</td>
        </tr>
    </tbody>
</table>
<div id="mojDiv" style="border:1px solid black"></div>

<script>
     $.get('@Url.Action("Index","AjaxIgre",new {id=Model.DeveloperID })', function (rezultat, status) {
        $("#mojDiv").html(rezultat);
    });
</script>

eStore_web/eStore_web/Views/Administrator/GetZahtjeveZaPremium.cshtml
@model List<eStore_web.EF_Models.PrijavaPremium>
@{
    ViewData["Title"] = "GetZahtjeveZaPremium";
}
<style>
    table {
        text-align: center;
    }
</style>
<h2>Zahtjevi za premium</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Kupac</th>
            <th>Datum zahtjeva</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>@item.Kupac.UserName</td>
                <td>@item.DatumPrijave</td>
                <td>
                    <a asp-action="PrihvatiPremium" asp-route-id="@item.Id" class="btn btn-success">Prihvati</a>
                    <a asp-action="OdbijPremium" asp-route-id="@item.Id" class="btn btn-warning">Odbij</a>

                </td>
            </tr>
        }
    </tbody>
</table>

eStore_web/eStore_web/Views/Administrator/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<a asp-action="OdobriGet">Lista neodobrenih igrica</a>
<br />
<a asp-action="Prikaz">Pregled developera</a>
<br />
<a asp-action="PrikazIgara">Pregled igara</a>
<br />
<a asp-action="PrikazRefundova">Zahtjevi za refund</a>
<br />
<a asp-action="GetZahtjeveZaPremium">Zahtjevi za premium</a>
<br />
<a asp-action="PregledReporta"> Pregled reporta</a>

eStore_web/eStore_web/Views/Administrator/OdobriGet.cshtml
@model List<eStore_web.EF_Models.Igra>
@{
    ViewData["Title"] = "OdobriGet";
}

<h2>Odobravanje igara</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Cijena</th>
            <th>Datum objave</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in @Model)
        {
            <tr>
                <td>@item.Naziv</td>
                <td>@item.Cijena</td>
                <td>@item.DatumObjave.ToShortDateString()</td>
                <td><a asp-action="OdobriSet" asp-route-id="@item.IgraID" class="btn btn-success">Odobri</a></td>
            </tr>
        }
    </tbody>
</table>

eStore_web/eStore_web/Views/Administrator/PregledIgara.cshtml
@*@model List<eStore_web.EF_Models.Igra>*@
@model eStore_web.ViewModel.PregledIgaraAdministratorVM
@{
    ViewData["Title"] = "PregledIgara";
    
}

<h2>Pregled igara za @Model.Developer</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <td>Naziv</td>
            <td>Opis</td>
            <td>Cijena</td>
            <td>Datum objave</td>
            <td>Odobrena</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in @Model.Igre)
        {
            <tr>
                <td>@x.Naziv</td>
                <td>@x.Opis</td>
                <td>@x.Cijena</td>
                <td>@x.DatumObjave</td>
                @if (x.Odobrena == true)
                {
                    <td><a asp-action="Zabrani" asp-route-id="@x.IgraID" class="btn btn-success">DA</a></td>
                }
                else
                {
                    <td><a asp-action="Odobri" asp-route-id="@x.IgraID" class="btn btn-danger">NE</a></td>
                }
            </tr>
        }
    </tbody>
</table>

eStore_web/eStore_web/Views/Administrator/PregledReporta.cshtml
@model List<eStore_web.ViewModel.AdministratorPregledReportaVM>
@{
    ViewData["Title"] = "PregledReporta";
}
<style>
    table {
        text-align: center;
    }
</style>
<h2>Pregled reporta</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Reportovani kupac</th>
            <th>Razlog reporta</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>@item.ReportovaniKupac</td>
                <td>@item.RazlogReporta</td>
                @if (item.Reputacija <= 10)
                {
                    <td><a asp-action="BanujKupca" asp-route-id="@item.KupacId" asp-route-reportId="@item.Id" class="btn btn-danger">Banuj</a></td>
                }
                else
                {
                    <td>
                        <a asp-action="BanujKupca" asp-route-id="@item.KupacId" asp-route-reportId="@item.Id" class="btn btn-danger">Banuj</a>
                        <a asp-action="SmanjiReputaciju" asp-route-id="@item.KupacId" asp-route-reportId="@item.Id" class="btn btn-warning">Smanji reputaciju</a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

eStore_web/eStore_web/Views/Administrator/Prikaz.cshtml
@using eStore_web.EF_Models

@{
    ViewData["Title"] = "Prikaz";
    var developeri = (List<Developer>)ViewData["lista-developera"];
}
<style>
    table {
        text-align: center;
    }
</style>
<h2>Banovanje</h2>
<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <td>Ime</td>
            <td>Prezime</td>
            <td>Naziv kompanije</td>
            <td>Banovan</td>
            <td>Akcija</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var x in developeri)
        {
            <tr>
                <td>@x.Osoba.Ime</td>
                <td>@x.Osoba.Prezime</td>

                <td>@x.NazivKompanije</td>
                <td>@(x.Banovan == true ? "DA" : "NE")</td>
                @if (x.Banovan == true)
                {
                    <td>
                        <a asp-action="Detalji" asp-route-DeveloperID="@x.DeveloperID" class="btn btn-info">Detalji</a>
                        <a asp-action="Unban" asp-route-DeveloperID="@x.DeveloperID" class="btn btn-warning">Unbanuj</a>
                    </td>
                }
                else
                {
                    <td>
                        <a asp-action="Detalji" asp-route-DeveloperID="@x.DeveloperID" class="btn btn-info">Detalji</a>
                        <a asp-action="Banuj" asp-route-DeveloperID="@x.DeveloperID" class="btn btn-warning">Banuj</a>
                    </td>
                }



            </tr>
        }
    </tbody>
</table>

eStore_web/eStore_web/Views/Administrator/PrikazIgara.cshtml
@model List<eStore_web.EF_Models.Igra>
@{
    ViewData["Title"] = "PrikazIgara";

    var porukagreska = (string)ViewData["poruka-greska"];
}
<h2>Prikaz igara</h2>
@if (porukagreska != null)
{
    <div class="alert alert-success" role="alert" id="porukaBox">
        @porukagreska
    </div>
}
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Naziv</td>
            <td>Zanr</td>
            <td>Kategorija</td>
            <td>Cijena</td>
            <td>Datum objave</td>
            <td>Premium status</td>
            <td>Akcija</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in @Model)
        {
            <tr>
                <td>@x.Naziv</td>
                <td>@x.GameGenre.NazivZanra</td>
                <td>@x.RatingCategorie.NazivKategorije</td>
                <td>@x.Cijena</td>
                <td>@x.DatumObjave.ToShortDateString()</td>
                @if (x.PremiumStatus == false)
                {
                    <td><a asp-action="PremiumOn" asp-route-id="@x.IgraID" class="btn btn-danger">NE</a></td>
                }
                else
                {
                    <td><a asp-action="PremiumOff" asp-route-id="@x.IgraID" class="btn btn-primary">DA</a></td>
           
                }
                <td><a asp-action="Uredi" asp-route-id="@x.IgraID" class="btn btn-info">Uredi</a></td>
            </tr>
        }

    </tbody>
</table>

eStore_web/eStore_web/Views/Administrator/PrikazRefundova.cshtml
@model List<eStore_web.EF_Models.Refund>
@{
    ViewData["Title"] = "PrikazRefundova";
}

<h2>PrikazRefundova</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Kupac</th>
            <th>Vrijeme kupovine</th>
            <th>Igra</th>
            <th>Razlog</th>
            <th>Akcija</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>@item.Kupac.Osoba.Ime @item.Kupac.Osoba.Prezime </td>
                <td>@item.VrijemeKupovine</td>
                <td>@item.Igra.Naziv</td>
                <td>@item.RazlogRefunda</td>
                <td>
                    <a asp-action="Prihvati" asp-route-id="@item.RefundID" class="btn btn-success">Prihvati</a>
                    <a asp-action="Odbij" asp-route-id="@item.RefundID" class="btn btn-warning">Odbij</a>
                </td>
            </tr>
        }
    </tbody>
</table>

eStore_web/eStore_web/Views/Administrator/Uredi.cshtml
@model eStore_web.ViewModel.AdministratorUrediVM
@{
    ViewData["Title"] = "UrediForm";

}

<h2>Uredi igru</h2>
<form asp-action="Uredi" method="post">
    <input type="hidden" asp-for="@Model.IgraId" value="@Model.IgraId" />
    <div class="form-group">
        <label asp-for="@Model.Naziv">Naziv</label>
        <input asp-for="@Model.Naziv" type="text" value="@Model.Naziv" class="form-control" />
        <span asp-validation-for="@Model.Naziv" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Cijena">Cijena</label>
        <input asp-for="@Model.Cijena" type="text" value="@Model.Cijena" class="form-control" />
        <span asp-validation-for="@Model.Cijena" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.DatumObjave">Datum objave</label>
        <input asp-for="@Model.DatumObjave" type="datetime" value="@Model.DatumObjave" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Opis">Opis</label>
        <input asp-for="@Model.Opis" type="text" value="@Model.Opis" class="form-control" />
        <span asp-validation-for="@Model.Opis" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Odobrena">Odobrena</label>
        <input asp-for="@Model.Odobrena" type="text" value="@Model.Odobrena" class="form-control" readonly />
        <span asp-validation-for="@Model.Odobrena" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.PremiumStatus">Premium</label>
        <input asp-for="@Model.PremiumStatus" type="text" value="@Model.PremiumStatus" class="form-control" readonly />
        <span asp-validation-for="@Model.PremiumStatus" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.ZanrId">Zanrovi</label>
        <select asp-for="@Model.ZanrId" asp-items="@Model.Zanrovi" class="form-control"></select>
        <span asp-validation-for="@Model.ZanrId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.KategorijaId">Kategorije</label>
        <select asp-for="@Model.KategorijaId" asp-items="@Model.Kategorije" class="form-control"></select>
        <span asp-validation-for="@Model.KategorijaId" class="text-danger"></span>
    </div>
    @Html.AntiForgeryToken()
    <input type="submit" value="Snimi" class="btn btn-primary" />
</form>

eStore_web/eStore_web/Views/Administrator/UrediForm.cshtml
@using eStore_web.EF_Models
@{
    ViewData["Title"] = "UrediForm";
    var igra = (Igra)ViewData["kljuc"];
    var zanrovi = (List<GameGenre>)ViewData["zanrove"];
    var kategorije = (List<RatingCategorie>)ViewData["kategorije"];
}

<h2>UrediForm</h2>
<form action="/Administrator/UrediSnimi" method="post">
    <input type="hidden" value="@igra.IgraID" name="IdPolje"/>
    <div class="form-group">
        <label>Naziv</label>
        <input type="text" class="form-control" name="NazivPolje" placeholder="Naziv" value="@igra.Naziv" />
    </div>
    <div class="form-group">
        <label>Cijena</label>
        <input type="text" class="form-control" name="CijenaPolje" placeholder="Cijena" value="@igra.Cijena" />
    </div>
    <div class="form-group">
        <label>Datum objave</label>
        <input type="text" class="form-control" name="DatumPolje" placeholder="Datum objave" value="@igra.DatumObjave" />
    </div>
    <div class="form-group">
        <label>Opis</label>
        <input type="text" class="form-control" name="OpisPolje" placeholder="Opis" value="@igra.Opis" />
    </div>
    <div class="form-group">
        <label>Premium status</label>
        <input type="text" class="form-control" name="PremiumPolje" placeholder="Premium" value="@igra.PremiumStatus" />
    </div>
    <div class="form-group">
        <label>Zanr</label>
        <select class="form-control" name="ZanrPolje">
            <option>--Odaberite zanr--</option>
            @foreach (GameGenre x in zanrovi)
            {
                if (x.GameGenreID == igra.GameGenreID)
                {
                    <option value="@x.GameGenreID" selected>@x.NazivZanra</option>
                }
                else
                {
                    <option value="@x.GameGenreID">@x.NazivZanra</option>
                }
            }

        </select>
    </div>
    <div class="form-group">
        <label>Kategorija</label>
        <select class="form-control" name="KategorijaPolje">
            <option>--Odaberite kategoriju--</option>
            @foreach (RatingCategorie x in kategorije)
            {
                if (x.RatingCategorieID == igra.RatingCategorieID)
                {
                    <option value="@x.RatingCategorieID" selected>@x.NazivKategorije</option>
                }
                else
                {
                    <option value="@x.RatingCategorieID">@x.NazivKategorije</option>
                }
            }

        </select>
    </div>
    <input type="submit" value="Snimi" />
</form>