eStore_web/eStore_web/Controllers/AutentifikacijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eStore_web.EF;
using Microsoft.AspNetCore.Mvc;
using eStore_web.Common;
using Microsoft.AspNetCore.Http;
using eStore_web.EF_Models;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace eStore_web.Controllers
{
    public class AutentifikacijaController : Controller
    {
        eContext db = new eContext();
       
      
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Register()
        {


            return View("Register");
        }
        public IActionResult RegisterSet(string Email, string AccountName, int TipRacuna, string NoviPassword1)
        {
            if (TipRacuna == 1)
            {
                Kupac Kupac = new Kupac()
                {
                    UserName = AccountName,
                    PretplacenNaPremium=true//privremeno su svi pretplaceni na premium
                };
                Kupac.Osoba = new Osoba();
                Kupac.Osoba.EmailAddress = new EmailAddress()
                {
                    Email = Email
                };
                Kupac.Osoba.LoginInfo = new LoginInfo()
                {
                    AccountName = AccountName,
                    Password = NoviPassword1,
                    TipKorisnika = 1
                };
                Kupac.Wallet = new Wallet()
                {
                    balance = 950//privremeno svi imaju nesto walleta..

                };
                db.Kupac.Add(Kupac);
                db.SaveChanges();

                return RedirectToAction("LoginSet", new { AccountName, password=NoviPassword1 });
            }
            if (TipRacuna == 2)
            {
                Developer Developer = new Developer();
                Developer.Osoba = new Osoba();
                Developer.Osoba.Ime = "unknown";
                Developer.Osoba.Prezime = "unknown";
                Developer.Osoba.EmailAddress = new EmailAddress()
                {
                    Email = Email
                };
                Developer.Osoba.LoginInfo = new LoginInfo() 
                {
                    AccountName = AccountName,
                    Password = NoviPassword1,
                    TipKorisnika = 2
                };
                db.Developer.Add(Developer);
                db.SaveChanges();

                return RedirectToAction("LoginSet", new { AccountName, NoviPassword1 });
            }


            TempData["error-key"] = "<br>Greska pri registraciji";
            return View("Register");

        }
        public IActionResult Login()
        {

            return View("Login");
        }
        public  IActionResult LoginSet(string AccountName, string password)
        {
            LoginInfo Log = db.LoginInfo.Where(li => li.AccountName == AccountName && li.Password == password)
                .FirstOrDefault();

            

            if (Log != null)
            {
                HttpContext.Session.SetObjectAsJson("LoggedUser", Log);
                HttpContext.Session.SetString("LoggedName", Log.AccountName);

                if (Log.TipKorisnika==1)
                    return RedirectToAction("Index", "Kupac");
                if (Log.TipKorisnika == 2)
                    return RedirectToAction("Index", "Developer");
                if (Log.TipKorisnika == 3)
                    return RedirectToAction("Index", "Administrator");
                else return null;
            }
            else
            {
                TempData["error-key"] = "<br>account name ili password pogresan";
                return View("Login");
            }
        }
       
        public IActionResult LogOut()
        {
            HttpContext.Session.SetObjectAsJson("LoggedUser",null);


            return RedirectToAction("Index", "Kupac");
        }
    }
}

eStore_web/eStore_web/Controllers/KupacController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using eStore_web.EF;
using eStore_web.EF_Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using eStore_web.Common;
using eStore_web.ViewModel;
using eStore_web.ViewComponents;

namespace eStore_web.Controllers
{
    public class KupacController : Controller
    {
        eContext db = new eContext();
      
        WishListManagment WishListManagment = new WishListManagment();
        PratiManagment PratiManagment = new PratiManagment();

        [Autorizacija(Kupac: true, Developer: true, Administrator: true, Svi: true)]
        public IActionResult Index(string pretraga = null, int sortirajPo = 1, int zanr = 0, int kategorija = 0,int from=0,int to=20)
        {

            


            #region DodjelVrijednosti

            KupacIndexVM kupacIndexVM = new KupacIndexVM()
            {
                pretraga = pretraga,
                sortirajPo = sortirajPo,
                zanr = zanr,
                kategorija = kategorija,
                from = from,
                to = to,
                gameGenre = db.GameGenre.ToList(),
                ratingCategorie=db.RatingCategorie.ToList()
            };
            #endregion

            #region PovratneVrijednosti
            ViewBag.kupacIndexVM = kupacIndexVM;
            return View("Index");
            #endregion
        }


        [Autorizacija(Kupac: true, Developer: true, Administrator: true, Svi: true)]
        public IActionResult LoadGames(string pretraga = null, int sortirajPo = 1, int zanr = 0, int kategorija = 0, int from = 0, int to = 20)
        {
            return ViewComponent("LoadGames", new { pretraga, sortirajPo, zanr, kategorija, from, to, db });
        }


        [Autorizacija(Kupac: true, Developer: true, Administrator: true, Svi: true)]
        public IActionResult Search(string pretraga)
        {

            return ViewComponent("Pretraga", new { pretraga = pretraga });
        }

        [Autorizacija(Kupac: true, Developer: false, Administrator: false, Svi: false)]
        public IActionResult DodajWishList(Kupac kupac, Igra igra)
        {
            List<WishList> WishList = db.WishList.Where(x => x.KupacID == kupac.KupacID).ToList();
            List<Recenzija> recenzija = db.Recenzija.Where(y => y.KupacID == kupac.KupacID).ToList();
            List<int> BrojElemenata = new List<int>();
            foreach (WishList x in WishList)
            {
                if (x.Igra.IgraID == x.Igra.IgraID)
                {
                    //Igra vec postoji
                }
            }
            WishList v = new WishList();
            v.KupacID = kupac.KupacID;
            v.IgraID = igra.IgraID;
            WishList.Add(v);
            return View();
        }

        [Autorizacija(Kupac: true, Developer: true, Administrator: true, Svi: true)]
        public IActionResult GameDetailes(int igraID)
        {
            #region dodjelaVrijednosti
            GameDetailesVM GameDetailesVM = new GameDetailesVM();
            double totalOcjena = 0;
            int brojRecenzija = 0;
            double novaCijena = 0;
            int KupacID = -1;
            #endregion dodjelaVrijednosti

            #region preuzimanjeKupca
            LoginInfo LoginInfo = HttpContext.Session.GetObjectFromJson<LoginInfo>("LoggedUser");
            if (LoginInfo != null)
            {
                if (LoginInfo.TipKorisnika == 1)
                {
                    Kupac Kupac = db.Kupac.Where(k => k.OsobaID == LoginInfo.OsobaID).FirstOrDefault();
                    if (Kupac != null)
                    {
                        KupacID = Kupac.KupacID;
                    }
                }
            }
            #endregion preuzimanjeKupca

            #region Preuzimanje_Igra_i_Popust
            Igra igra = db.Igra.Where(i => i.IgraID == igraID)
                .FirstOrDefault();
            Popust popust = db.Popust.Where(p => p.PocetakPopusta <= DateTime.Now && p.KrajPopusta>=DateTime.Now && p.IgraID==igraID).FirstOrDefault();


            if (popust != null && igra != null)
            {
                float procent = 1 - (float)popust.PopustProcent / 100;

                novaCijena = Math.Round((igra.Cijena * procent), 2);
            }


            #endregion Preuzimanje_Igra_i_Popust

            #region recenzije
            totalOcjena = (from ig in db.Recenzija
                           where ig.IgraID == igraID
                           select ig.Ocjena).Sum();

            brojRecenzija = (from ig in db.Recenzija
                             where ig.IgraID == igraID
                             select ig.Ocjena).Count();

            totalOcjena /= brojRecenzija;

            

            List<Recenzija> recenzije = db.Recenzija.Where(r => r.IgraID == igra.IgraID)
                .Include(r=>r.Kupac)
                .ThenInclude(k=>k.Osoba)
                .ThenInclude(o=>o.OsobaImage)
                .ToList();
            GameDetailesVM.Recenzije = recenzije;
            #endregion recenzije

            #region punjenjeVM
            GameDetailesVM.Igra = igra;
            GameDetailesVM.Popust = popust;
            GameDetailesVM.NovaCijena = novaCijena;
            GameDetailesVM.Ocjena = totalOcjena;
            GameDetailesVM.ImaIgru = ImaIgru(KupacID, igraID);
            GameDetailesVM.ImaWishList = WishListManagment.ImaWishList(igraID, KupacID);
            GameDetailesVM.ImaRecenziju = ImaRecenziju(KupacID, igraID);
            GameDetailesVM.GameTrailer = igra.TrailerUrl;
            //.....
            GameDetailesVM.PratiIgru = PratiManagment.PratiIgru(igraID,KupacID);

            #endregion punjenjeVM



            ViewBag.GameDetailesVM = GameDetailesVM;
            return View("GameDetailes");
        }

        [Autorizacija(Kupac: true, Developer: false, Administrator: false, Svi: false)]
        public bool  DodajRecenzija(int KupacID,int IgraID,int Ocjena,string textarea)
        {
            Kupac Kupac = db.Kupac.Where(k => k.KupacID == KupacID).FirstOrDefault();
            Igra Igra = db.Igra.Where(i => i.IgraID == IgraID).FirstOrDefault();
            if (Kupac == null || Igra == null || (Ocjena < 1 || Ocjena > 5 || textarea == null))
                return false;


            Recenzija recenzija = new Recenzija()
            {
                Kupac = Kupac,
            Igra=Igra,
            Ocjena=Ocjena,
            RecenzijaText=textarea,
            //Treba dodat u bp
            //DatumObjave=DateTime.Now
            
            };
            db.Recenzija.Add(recenzija);
            db.SaveChanges();
            db.Dispose();

           
            return true;
        }

        //idk
        public bool Upload(int IgraID,IFormFile Image)
        {
            FileManagment p = new FileManagment();
            return p.DodajSliku(IgraID, 0, Image, db);

        }


        [Autorizacija(Kupac: true, Developer: false, Administrator: false, Svi: false)]
        public IActionResult KupiIgru(int KupacID,int IgraID)
        {
            LoginInfo Log = HttpContext.Session.GetObjectFromJson<LoginInfo>("LoggedUser");

            Kupac kupac = db.Kupac.Where(k => k.OsobaID == Log.OsobaID).FirstOrDefault();

            KupacID = kupac.KupacID;

            if (ImaIgru(KupacID,IgraID))
            {
                return RedirectToAction("GameDetailes", new { IgraID });
            }
           
        
            Kupac Kupac = db.Kupac.Where(k => k.KupacID == KupacID)
                .Include(w=>w.Wallet)
                .FirstOrDefault();
            Igra Igra = db.Igra.Where(i => i.IgraID == IgraID).FirstOrDefault();
            //Popust Popust = db.Popust.Where(p => p.Aktivan == true && p.IgraID == IgraID).FirstOrDefault();

            if (Igra.Cijena < Kupac.Wallet.balance)
            {
                KupacKupuje kupacKupuje = new KupacKupuje()
                {
                    Igra = Igra,
                    Kupac = Kupac,
                    Cijena = Igra.Cijena,
                    VrijemeKupovine = DateTime.Now
                };
                WalletHistory walletHistory = new WalletHistory()
                {
                    WalletID = Kupac.Wallet.WalletID,
                    IsIgra = true,
                    TransactionAmount = (double)Igra.Cijena * (-1),
                    CurrentBalance = Kupac.Wallet.balance - Igra.Cijena,
                    IgraID=IgraID
                };



                db.WalletHistory.Add(walletHistory);

                RemoveWishList(IgraID, KupacID);
                Kupac.Wallet.balance -= Igra.Cijena;
                db.KupacKupuje.Add(kupacKupuje);
                db.SaveChanges();
                db.Dispose();
            }
            else
            {
                TempData["error-key"] = "<br> No monie boi";
            }
            return RedirectToAction("GameDetailes", new { IgraID });
        }


        [Autorizacija(Kupac: true, Developer: false, Administrator: false, Svi: false)]
        public IActionResult PreuzmiIgru(int KupacID,int IgraID)
        {
            if (ImaIgru(KupacID, IgraID))
            {
                return RedirectToAction("GameDetailes", new { IgraID });
            }

            Kupac Kupac = db.Kupac.Where(k => k.KupacID == KupacID)
                .Include(k=>k.Wallet)
                .FirstOrDefault();
            Igra Igra = db.Igra.Where(i => i.IgraID == IgraID).FirstOrDefault();

            if(Igra.PremiumStatus==true && Kupac.PretplacenNaPremium==true)
            {
                PreuzimanjeIgre preuzimanjeIgre = new PreuzimanjeIgre()
                {
                    Igra = Igra,
                    Kupac = Kupac,
                    VrijemePreuzimanja = DateTime.Now
                };

                WalletHistory walletHistory = new WalletHistory()
                {

eStore_web/eStore_web/Views/Shared/_Layout.cshtml
@using eStore_web.EF_Models;
@using Microsoft.AspNetCore.Mvc;
@using eStore_web.Common;
@using Microsoft.AspNetCore.Http;
@using Microsoft.EntityFrameworkCore;

@{ 
    LoginInfo Log = Context.GetLogiraniKorisnik();
    Kupac Kup=null;
    Developer Dev=null;
    Administrator Admin=null;
    if (Log != null)
    {
        if (Log.TipKorisnika == 1)
        {
            Kup = Context.GetLogiraniKorisnikAll<Kupac>();
        }
        if (Log.TipKorisnika == 2)
        {
            Dev = Context.GetLogiraniKorisnikAll<Developer>();
        }
        if (Log.TipKorisnika == 3)
        {
            Admin = Context.GetLogiraniKorisnikAll<Administrator>();
        }
    }
}
<script>

    

</script>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eStore_web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/css/mLayoutPage.css" !important>

    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script src="/js/site.js"></script>
    <script src="~/js/jsAjax.js"></script>

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

</head>
<body>
    
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">eStore</a>
                </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Kupac" asp-action="Index">Store</a></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    @*dodano dropdown*@
                    @if (Log != null)
                    {
                        <ul class="nav navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">notifications</i>
                                    <span id="NotificationBrojac" class="notification"></span>
                                </a>
                                <div id="notifikacije" class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink" style="padding:5px">



                                </div>
                            </li>
                        </ul>
                    }
                    @if (Log == null)
                    {

                        <li><a asp-area="" asp-controller="Autentifikacija" asp-action="Login">LogIn</a></li>
                        <li><a asp-area="" asp-controller="Autentifikacija" asp-action="Register">Register</a></li>

                    }
                    else
                    {

                        if (Log.TipKorisnika == 1)
                        {

                            <li class="">
                                <div class="mUser">
                                    @if (Kup.Osoba.OsobaImage != null)
                                    {
                                        var base64 = Convert.ToBase64String(Kup.Osoba.OsobaImage.Image);
                                        var imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                                        <img src="@imgsrc">
                                    }
                                    else
                                    {
                                        <img src="~/images/profileDemo.png">
                                    }

                                    @Html.ActionLink(Log.AccountName, "Index", "Profile", new { KupacID = Kup.KupacID })
                                    @Html.ActionLink(Math.Round(Kup.Wallet.balance, 2).ToString() + " KM", "Index", "Profile", new { KupacID = Kup.KupacID })




                                    <button class=" dropdown-toggle mLayoutDropDownButton" type="button" data-toggle="dropdown">

                                        <span class="caret" style="text-align:center;"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-header">profil</li>
                                        <li>@Html.ActionLink("Moj profil", "Index", "Profile", new { KupacID = Kup.KupacID })</li>
                                        <li>@Html.ActionLink("Uredi profil", "EditProfile", "Profile", new { KupacID = Kup.KupacID })</li>
                                        <li>@Html.ActionLink("Wallet", "WalletHistory", "Profile", new { KupacID = Kup.KupacID })</li>
                                        <li class="divider"></li>
                                        <li class="dropdown-header">sesija</li>
                                        <li><a href="#" disabled>Aktivne sesije</a></li>
                                        <li class=""><a asp-area="" asp-controller="Autentifikacija" asp-action="LogOut">LogOut</a></li>
                                    </ul>



                                </div>
                            </li>
                        }
                        if (Log.TipKorisnika == 2)
                        {

                            <li class="">
                                <div class="mUser">
                                    <img src="~/images/profileDemo.png" />

                                    @Html.ActionLink(Log.AccountName, "Index", "Kupac")


                                </div>
                            </li>

                        }
                        if (Log.TipKorisnika == 3)
                        {

                            <li class="">
                                <div class="mUser">
                                    <img src="~/images/profileDemo.png" />

                                    @Html.ActionLink(Log.AccountName, "Index", "Kupac")


                                </div>
                            </li>

                        }


                    }
                </ul>


                


            </div>
               
        </div>
    </nav>
            
            
     <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/signalRNotifikacije.js"></script>



            <partial name="_CookieConsentPartial" />

            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; 2018 - eStore_web</p>
                </footer>
            </div>

            <environment include="Development">
                <script src="~/lib/jquery/dist/jquery.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
                <script src="~/js/site.js" asp-append-version="true"></script>
            </environment>
            <environment exclude="Development">
                <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery"
                        crossorigin="anonymous"
                        integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
                </script>
                <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                        crossorigin="anonymous"
                        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
                </script>
                <script src="~/js/site.min.js" asp-append-version="true"></script>
            </environment>

            @RenderSection("Scripts", required: false)
</body>
</html>

eStore_web/eStore_web/Views/Shared/_LayoutAutentifikacija.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eStore_web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <style>
        body {
            min-height: 100%
        }
        html {
            height: 100%
        }

      
    </style>
</head>
<body>
    

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - eStore_web</p>
        </footer>
    </div>
  



</body>
</html>

eStore_web/eStore_web/Views/Shared/_LayoutEditProfile.cshtml
@using eStore_web.EF_Models;
@using Microsoft.AspNetCore.Mvc;
@using eStore_web.Common;
@using Microsoft.AspNetCore.Http;
@using Microsoft.EntityFrameworkCore;

@{
    LoginInfo Log = Context.GetLogiraniKorisnik();
    Kupac Kup = null;
    Developer Dev = null;
    Administrator Admin = null;
    if (Log != null)
    {
        if (Log.TipKorisnika == 1)
        {
            Kup = Context.GetLogiraniKorisnikAll<Kupac>();
        }
        if (Log.TipKorisnika == 2)
        {
            Dev = Context.GetLogiraniKorisnikAll<Developer>();
        }
        if (Log.TipKorisnika == 3)
        {
            Admin = Context.GetLogiraniKorisnikAll<Administrator>();
        }
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eStore_web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link rel="stylesheet" href="~/css/mLayoutPage.css">



</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">eStore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Kupac" asp-action="Index">Store</a></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    @if (Log == null)
                    {
                        <li><a asp-area="" asp-controller="Autentifikacija" asp-action="Login">LogIn</a></li>
                        <li><a asp-area="" asp-controller="Autentifikacija" asp-action="Register">Register</a></li>
                    }
                    else
                    {
                        if (Log.TipKorisnika == 1)
                        {

                            <li class="">
                                <div class="mUser">
                                    
                                    @if (Kup.Osoba.OsobaImage != null)
                                    {
                                        var base64 = Convert.ToBase64String(Kup.Osoba.OsobaImage.Image);
                                        var imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                                        <img src="@imgsrc">
                                    }
                                    else
                                    {
                                        <img src="~/images/profileDemo.png">
                                    }
                                    @Html.ActionLink(Log.AccountName, "Index", "Profile", new { KupacID = Kup.KupacID })
                                    @Html.ActionLink(Math.Round(Kup.Wallet.balance, 2).ToString() + " KM", "Index", "Profile", new { KupacID = Kup.KupacID })








                                </div>
                            </li>

                        }
                        if (Log.TipKorisnika == 2)
                        {

                            <li class="">
                                <div class="mUser">
                                    <img src="~/images/profileDemo.png" />

                                    @Html.ActionLink(Log.AccountName, "Index", "Kupac")


                                </div>
                            </li>

                        }
                        if (Log.TipKorisnika == 3)
                        {

                            <li class="">
                                <div class="mUser">
                                    <img src="~/images/profileDemo.png" />

                                    @Html.ActionLink(Log.AccountName, "Index", "Kupac")


                                </div>
                            </li>

                        }

                        }

                </ul>

            </div>

        </div>
    </nav>






    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - eStore_web</p>
        </footer>
    </div>

 

    @RenderSection("Scripts", required: false)
</body>
</html>